user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;

    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;

    # Frontend Configuration
    server {
        listen 85;
        server_name Logiq.yuvaq.com  192.168.13.86;

        root /usr/share/nginx/html/; # Correct path to dist folder
        index index.html;

        location / {
            try_files $uri /index.html;
        }

        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|mp4|webm|ogg|mp3|wav|m4a|aac|ogv|avi|mov|wmv|flv|mkv)$ {
            expires 6M;
            access_log off;
            add_header Cache-Control "public";
            try_files $uri /index.html;
        }

        error_page 404 /index.html;

        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
    }

    # Backend Configuration
    server {
        listen 86;
        server_name Logiqbe.yuvaq.com;

        location / {
            proxy_pass http://192.168.13.72:5000/rr_seechange_fe:3000; # Replace with actual backend service name or IP
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
    }
}